### ISSUE TITLE
Not working in my computer :/

### ISSUE THREAD

**Issue by Shalol** [devocalypse/BoneEditor#2]
Hey!, this mods looks awesome, but i have one little problem, instead of using commas (example: 0,5 if you want a bone to be half as long as before) the mod is using periods (0.5) and that is messing with the bones. Maybe is because im from Spain and my pc works differently.

Is there any way to fix this?, THANKS :D

**Comment by devocalypse** [comment]
delphist2008 submitted a patch for that. I merged it but forgot to publish the new release version.
Get version 1.1 from releases and it should work.
Thanks for reminding me.
